### ISSUE TITLE
saves do not work in all games.

### ISSUE THREAD

**Issue by Anarhist8BIT** [vrodin/Burn2Slot#1]
saves do not work in all games.
some games are started, but the save is lost, the battery is working, I tried it on different cartridges and different games. some immediately after starting the game writes - Your saved data is corrupted
https://ibb.co/Jj9mcgM
https://sun9-24.userapi.com/impg/V_g8PXqEGjwZUoEghx_qmocXHhWkqhZevAqE0Q/61RL6TQut2Y.jpg?size=900x1600&quality=96&sign=3fd9103e47caf44f12a1b58d735cdbf0&type=album

**Comment by vrodin** [comment]
Firstly take picture of you card. Try flash GBATA SRAM patched ROMs

**Comment by Anarhist8BIT** [comment]
@vrodin https://sun9-40.userapi.com/impg/2XJU4ioe1LvRylU1Kq-PAXpG4JkkogoffaNfOQ/JgIFBQzorZo.jpg?size=900x1600&quality=96&sign=09a034d92b5442700a0c585099ee43bf&type=album
game running, saving not working, error.
https://sun9-58.userapi.com/impg/eNN95-EubD7g-zFeQMezCpHEulSu-HaK-b6Yhw/xZ2U0C30Ff0.jpg?size=900x1600&quality=96&sign=01d2a92888f65e9ac0a71104b3cb8303&type=album
https://sun9-34.userapi.com/impg/NbTcn309O_RLjs-G3wuDs9Dd-1DjeE6SyjbfiA/QTr8nj6QWh0.jpg?size=1600x900&quality=96&sign=5d1ed31d12050ae505aaeb803f255766&type=album
https://sun9-15.userapi.com/impg/jLZxLmsDFnyNfDKzQAEC0xmxzlzWA13KeR87tw/YRTWr9hto3w.jpg?size=900x1600&quality=96&sign=04ba2b9f42a95532093958f6a5d30e5a&type=album
https://sun9-63.userapi.com/impg/TxOMayoB5x_qLkBfwRijpOLM9wb_obeVWgJu4A/eQCLOnAaIKM.jpg?size=900x1600&quality=96&sign=4324221e6f88c75f6bcc147d8ed293b1&type=album

**Comment by Anarhist8BIT** [comment]
GBATA SRAM patched ROMs helped

 thanks
