### ISSUE TITLE
record Classic NES - Super Mario Bros

### ISSUE THREAD

**Issue by Anarhist8BIT** [vrodin/Burn2Slot#3]
Hi, can you please tell me if it is possible to record Classic NES - Super Mario Bros.? the gbata7a-en program did a sram patch, but still an error.
https://sun9-5.userapi.com/impg/4wCNKWxJJX62MQyCQ1Eh4rrmRku8otLi2Fqyhw/g1F-Hk5xFyM.jpg?size=1280x576&quality=96&sign=236b159f7fe7e39cb726d97c9aaf91a2&type=album

**Comment by vrodin** [comment]
try any other rom. maybe wowroms help u
